# Generated by Django 5.2.1 on 2025-05-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0003_remove_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
