# Generated by Django 5.2.1 on 2025-05-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0004_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
    ]
