# Generated by Django 5.2.1 on 2025-05-14 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0005_remove_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_id',
        ),
    ]
