# Generated by Django 5.2.1 on 2025-05-15 02:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0006_remove_account_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposithistory',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='withdrawalhistory',
            name='date',
        ),
        migrations.AddField(
            model_name='deposithistory',
            name='crypto',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('TRX', 'Tron'), ('DOGE', 'Doge'), ('BCH', 'Bitcoin Cash'), ('USDT_TRC20', 'USDT TRC20'), ('BNB', 'Binance Coin'), ('LTC', 'Litecoin'), ('USDT_ERC20', 'USDT ERC20'), ('BUSD', 'Binance USD')], default='BTC', max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawalhistory',
            name='crypto',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('TRX', 'Tron'), ('DOGE', 'Doge'), ('BCH', 'Bitcoin Cash'), ('USDT_TRC20', 'USDT TRC20'), ('BNB', 'Binance Coin'), ('LTC', 'Litecoin'), ('USDT_ERC20', 'USDT ERC20'), ('BUSD', 'Binance USD')], default='BTC', max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawalhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deposithistory',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdrawalhistory',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
