# Generated by Django 5.2.1 on 2025-05-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0008_alter_account_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='binance_usd_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='bitcoin_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='bitcoin_cash_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='bnb_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='doge_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='ethereum_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='litecoin_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='tron_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='usdt_erc20_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='usdt_trc20_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
    ]
