# Generated by Django 5.2.1 on 2025-05-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0009_alter_account_binance_usd_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposithistory',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='withdrawalhistory',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
