# Generated by Django 5.2.1 on 2025-05-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0010_alter_deposithistory_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='nationality',
            field=models.CharField(blank=True, choices=[('Afghanistan', 'Afghanistan'), ('Albania', 'Albania'), ('Algeria', 'Algeria'), ('Andorra', 'Andorra'), ('Angola', 'Angola'), ('Argentina', 'Argentina'), ('Zimbabwe', 'Zimbabwe')], max_length=100, null=True),
        ),
    ]
