# Generated by Django 5.2.1 on 2025-05-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0020_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='amount_invested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
