# Generated by Django 5.2.1 on 2025-05-19 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0021_investment_amount_invested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='amount_invested',
        ),
    ]
