# Generated by Django 5.2.1 on 2025-05-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0022_remove_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
