# Generated by Django 5.2.1 on 2025-05-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0023_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='investment',
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
