# Generated by Django 5.2.1 on 2025-05-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0024_remove_account_investment_alter_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gold_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='account',
            name='iron_ore_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='account',
            name='lithium_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='account',
            name='steel_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
    ]
