# Generated by Django 5.2.1 on 2025-06-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0025_account_gold_balance_account_iron_ore_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='binance_usd_balance',
            new_name='gold',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='bitcoin_balance',
            new_name='iron_ore',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='bitcoin_cash_balance',
            new_name='kaolin',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='bnb_balance',
            new_name='lithium',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='doge_balance',
            new_name='steel',
        ),
        migrations.RemoveField(
            model_name='account',
            name='ethereum_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='gold_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='iron_ore_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='litecoin_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='lithium_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='steel_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='tron_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='usdt_erc20_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='usdt_trc20_balance',
        ),
        migrations.AlterField(
            model_name='deposithistory',
            name='crypto',
            field=models.CharField(choices=[('FORGEX', 'Steel'), ('FEVAULT', 'Iron Ore'), ('CHARGECOIN', 'Lithium'), ('AUXCOIN', 'Gold'), ('WHITEEARTH', 'Kaolin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalhistory',
            name='crypto',
            field=models.CharField(choices=[('FORGEX', 'Steel'), ('FEVAULT', 'Iron Ore'), ('CHARGECOIN', 'Lithium'), ('AUXCOIN', 'Gold'), ('WHITEEARTH', 'Kaolin')], max_length=20),
        ),
    ]
