deployment:
  tasks:
    - task: deploy
      command: |
        echo "Starting deployment"
        pip install -r requirements.txt
        python manage.py migrate
        python manage.py collectstatic --noinput
        echo "Deployment completed!"
